# Thorn PvP Barbarian: https://maxroll.gg/d4/planner/2e2up00s
Aspect:
  - [needleflare_aspect, 40]
  - [death_wish_aspect] 
  - [aspect_of_berserk_ripping, 30]
  - [bold_chieftain's_aspect, 1.9]

Affixes:
  - Gloves:
      itemType: gloves
      minPower: 800
      affixPool:
        - [all_stats]
        - [attack_speed]
        - [strength]
        - [lucky_hit_chance]
      minAffixCount: 3

  - Boots:
      itemType: boots
      minPower: 800
      affixPool:
        - [movement_speed]
        - [all_stats]
        - [strength]
        - [damage_reduction_while_injured]
      minAffixCount: 3

  - WeaponTwoHanded:
      itemType: [two-handed mace, two-handed axe]
      minPower: 800
      affixPool:
        - [damage_while_berserking]
        - [damage_to_close_enemies]
        - [all_stats]
        - [strength]
      minAffixCount: 3

  - WeaponDualWield:
      itemType: [axe]
      minPower: 900
      affixPool:
        - [damage_while_berserking]
        - [damage_to_close_enemies]
        - [all_stats]
        - [strength]
      minAffixCount: 3

  - Amulet:
      itemType: amulet
      minPower: 800
      affixPool:
        - [ranks_of_the_tough_as_nails_passive]
        - [strength]
        - [damage_reduction]
        - [damage_reduction_from_close_enemies]
      minAffixCount: 3

  - RingThorn:
      itemType: ring
      minPower: 800
      affixPool:
        - [maximum_life]
        - [damage_to_close_enemies]
        - [damage_while_berserking]
        - [physical_damage]
      minAffixCount: 3

  


