# Source: https://d4builds.gg/database/uniques/

Uniques:
  - Blue Rose:
      itemType: ring
      minPower: 860
      affixPool:
        - [critical_strike_damage]
        - [ice_spike_damage]
        - [lucky_hit_chance]
        - [mana_cost_reduction]
      aspectValue: 0.25

  - Esadoras Overflowing Cameo:
      itemType: amulet
      minPower: 860
      affixPool:
        - [cooldown_reduction]
        - [crackling_energy_damage]
        - [ranks_of_the_shocking_impact_passive]
        - [movement_speed]

  - Esus Heirloom:
      itemType: boots
      minPower: 850
      affixPool:
        - [movement_speed]
        - [damage_for_seconds_after_killing_an_elite]
        - [shrine_buff_duration]
        - [critical_strike_damage]
      aspectValue: 20

  - Flamescar:
      itemType: wand
      minPower: 900
      affixPool:
        - [mana_cost_reduction]
        - [damage_to_burning_enemies]
        - [lucky_hit_chance_with_fire_damage]
        - [ranks_of_incinerate]

  - Gloves of the Illuminator:
      itemType: gloves
      minPower: 860
      affixPool:
        - [critical_strike_chance]
        - [fireball_attack_speed]
        - [lucky_hit_up_to_a_chance_to_restore_primary_resource]
        - [ranks_of_fireball]
      aspectValue: [35, "smaller"]

  - Iceheart Brais:
      itemType: pants
      minPower: 850
      affixPool:
        - [maximum_life]
        - [damage_to_frozen_enemies]
        - [damage_reduction]
        - [freeze_duration]
      aspectValue: 11

  - Raiment of the Infinite:
      itemType: chest armor
      minPower: 850
      affixPool:
        - [intelligence]
        - [damage_to_close_enemies]
        - [damage_to_stunned_enemies]
        - [ranks_of_the_glass_cannon_passive]
      aspectValue: 2

  - Staff of Endless Rage:
      itemType: staff
      minPower: 850
      affixPool:
        - [core_skill_damage]
        - [damage_to_close_enemies]
        - [fire_damage_ranks_of_the_inner_flames_passive]
      aspectValue: 20

  - The Oculus:
      itemType: staff
      minPower: 900
      affixPool:
        - [max_evade_charges]
        - [attacks_reduce_evades_cooldown_by_seconds]
        - [damage]
        - [ranks_of_teleport]
