Aspect: 
  # Thorn barb
  - [needleflare_aspect, 40]
  - death_wish_aspect 
  - [aspect_of_berserk_ripping, 30]
  - [bold_chieftain's_aspect, 1.9]

Affixes:
  - GlovesThorn:
      itemType: gloves
      minPower: 780
      affixPool:
        - [all_stats]
        - [attack_speed]
        - [strength]
        - [damage_to_injured_enemies]
      minAffixCount: 3

  - Armor:
      itemType: [chest armor, pants]
      minPower: 780
      affixPool:
        - [damage_reduction_from_close_enemies]
        - [damage_reduction_while_fortified]
        - [lightning_resistance]
        - [total_armor]
        - [maximum_life]
        - [damage_reduction_from_enemies_that_are_bleeding]
      minAffixCount: 3

  - Boots:
      itemType: boots
      minPower: 780
      affixPool:
        - [movement_speed]
        - [cold_resistance]
        - [fire_resistance]
        - [lightning_resistance]
        - [poison_resistance]
        - [shadow_resistance]
        - [damage_reduction_while_injured]
      minAffixCount: 3

  - WeaponThornTwoHanded:
      itemType: [two-handed mace, two-handed sword, two-handed axe]
      minPower: 900
      affixPool:
        - [damage_while_berserking]
        - [damage_to_close_enemies]
        - [all_stats]
        - [strength]
      minAffixCount: 3

  - WeaponThornDualWield:
      itemType: [sword, axe, mace]
      minPower: 900
      affixPool:
        - [damage_while_berserking]
        - [damage_to_close_enemies]
        - [all_stats]
        - [strength]
      minAffixCount: 3

  - Amulet:
      itemType: amulet
      minPower: 780
      affixPool:
        - [cooldown_reduction]
        - [ranks_of_the_tough_as_nails_passive]
        - [strength]
        - [movement_speed]
      minAffixCount: 3

  - RingThorn:
      itemType: ring
      minPower: 780
      affixPool:
        - [maximum_life]
        - [damage_to_close_enemies]
        - [damage_while_berserking]
        - [physical_damage]
      minAffixCount: 3

  


