Aspects:
  - [aspect_of_bursting_venoms]
  - [aspect_of_corruption, 40]
  - [aspect_of_elusive_menace, 7]
  - [aspect_of_pestilent_points, 150]
  - [aspect_of_noxious_ice, 29]
  - [aspect_of_repeating, 45]
  - [bladedancers_aspect, 15]
  - [assimilation_aspect, 10]
  - [cheats_aspect, 25]
  - [energizing_aspect, 9]
  - [enshrouding_aspect, 4]
  - [frostbitten_aspect, 25]
  - [manglers_aspect, 45]
  - [ravenous_aspect, 65]
  - [umbrous_aspect, 59]


Affixes:
  - Helm:
      itemType: helm
      minPower: 800
      affixPool:
        - [basic_skill_attack_speed, 6]
        - [cooldown_reduction, 5]
        - [dexterity, 36]
        - [maximum_life, 580]
        - [total_armor, 9]
        - [ranks_of_poison_imbuement, 3]
        - [ranks_of_shadow_imbuement, 3]
      minAffixCount: 3

  - Gloves:
      itemType: gloves
      minPower: 800
      affixPool:
        - [attack_speed, 7]
        - [dexterity, 38]
        - [lucky_hit_chance, 7.8]
        - [critical_strike_chance, 5.5]
        - [ranks_of_twisting_blades, 3]
        - [ranks_of_rapid_fire, 3]
      minAffixCount: 3

  - Boots:
      itemType: boots
      minPower: 800
      affixPool:
        - [movement_speed, 16]
        - [dexterity, 40]
        - [dodge_chance, 5]
        - [energy_cost_reduction, 6]
      minAffixCount: 3

  - Amulet:
      itemType: amulet
      minPower: 725
      affixPool:
        - [cooldown_reduction, 6]
        - [damage_reduction, 6]
        - [damage_reduction_from_close_enemies, 10]
        - [damage_reduction_from_distant_enemies, 12]
        - [total_armor, 9]
        - [energy_cost_reduction, 6]
        - [movement_speed]
        - [ranks_of_all_imbuement_skills, 2]
        - [ranks_of_the_exploit_passive, 2]
        - [ranks_of_the_weapon_mastery_passive, 2]
        - [ranks_of_the_malice_passive, 2]
        - [ranks_of_the_frigid_finesse_passive, 2]
        - [ranks_of_the_deadly_venom_passive, 2]
      minAffixCount: 3

  - Ring:
      itemType: ring
      minPower: 725
      affixPool:
        - [critical_strike_chance, 4]
        - [lucky_hit_chance, 5]
        - [resource_generation, 8]
        - [maximum_life, 680]
        - [damage_to_crowd_controlled_enemies, 9]
      minAffixCount: 3

  - WeaponClose:
      itemType: [dagger, sword]
      minPower: 915
      affixPool:
        - [all_stats, 22]
        - [dexterity, 44]
        - [core_skill_damage, 17]
        - [damage_to_close_enemies, 19]
        - [vulnerable_damage, 16]
      minAffixCount: 2

  - WeaponFar:
      itemType: [crossbow]
      minPower: 725
      affixPool:
        - [all_stats, 44]
        - [dexterity, 90]
        - [core_skill_damage, 25]
        - [damage_to_close_enemies, 37]
        - [vulnerable_damage, 34]
      minAffixCount: 3
