# Source: https://d4builds.gg/database/uniques/

Uniques:
  - Black River:
      itemType: scythe
      minPower: 900
      affixPool:
        - [intelligence]
        - [ranks_of_all_corpse_skills]
        - [ranks_of_the_hewed_flesh_passive]
        - [ranks_of_the_fueled_by_death_passive]
      aspectValue:

  - Blood Artisans Cuirass:
      itemType: chest armor
      minPower: 850
      affixPool:
        - [damage_for_seconds_after_picking_up_a_blood_orb]
        - [blood_orb_healing]
        - [maximum_life]
        - [ranks_of_bone_spirit]
      aspectValue: [10, "smaller"]

  - Blood Moon Breeches:
      itemType: pants
      minPower: 850
      affixPool:
        - [maximum_life]
        - [ranks_of_all_curse_skills]
        - [ranks_of_the_amplify_damage_passive]
        - [damage_reduction_from_enemies_affected_by_curse_skills]
      aspectValue: 3

  - Bloodless Scream:
      itemType: two-handed scythe
      minPower: 900
      affixPool:
        - [darkness_skill_damage]
        - [damage_to_chilled_enemies]
        - [intelligence]
        - [cold_resistance]
      aspectValue: 20

  - Deathless Visage:
      itemType: helm
      minPower: 850
      affixPool:
        - [damage_reduction]
        - [physical_damage]
        - [critical_strike_damage_with_bone_skills]
        - [maximum_essence]

  - Deathspeakers Pendant:
      itemType: amulet
      minPower: 870
      affixPool:
        - [blood_skill_damage]
        - [summoning_skill_damage]
        - [essence_cost_reduction]
        - [ranks_of_the_coalesced_blood_passive]

  - Greaves of the Empty Tomb:
      itemType: boots
      minPower: 850
      affixPool:
        - [movement_speed]
        - [essence_cost_reduction]
        - [lucky_hit_chance_with_shadow_damage]
        - [damage_reduction_from_enemies_that_are_affected_by_shadow_damage_over_time]

  - Howl from Below:
      itemType: gloves
      minPower: 860
      affixPool:
        - [lucky_hit_chance]
        - [corpse_skill_attack_speed]
        - [lucky_hit_up_to_a_chance_to_stun]
        - [lucky_hit_up_to_a_chance_to_fear]
      aspectValue: 30

  - Lidless Wall:
      itemType: shield
      minPower: 860
      affixPool:
        - [attack_speed]
        - [maximum_life]
        - [maximum_essence]
        - [lucky_hit_up_to_a_chance_to_restore_primary_resource]
      aspectValue: 10

  - Ring of Mendeln:
      itemType: ring
      minPower: 860
      affixPool:
        - [lucky_hit_chance]
        - [minion_attack_speed]
        - [maximum_minion_life]
        - [thorns]
