# Source: https://d4builds.gg/database/uniques/

Uniques:
  - Dolmen Stone:
      itemType: amulet
      minPower: 870
      affixPool:
        - [maximum_life]
        - [resource_generation]
        - [nature_magic_skill_cooldown_reduction]
        - [ranks_of_all_wrath_skills]

  - Fleshrender:
      itemType: mace
      minPower: 900
      affixPool:
        - [damage_while_shapeshifted]
        - [damage_to_poisoned_enemies]
        - [core_skill_damage]
        - [ranks_of_all_defensive_skills]

  - Greatstaff of the Crone:
      itemType: staff
      minPower: 900
      affixPool:
        - [damage_to_close_enemies]
        - [damage_to_crowd_controlled_enemies]
        - [nonphysical_damage]
        - [ranks_of_claw]
      aspectValue: 120

  - Hunters Zenith:
      itemType: ring
      minPower: 860
      affixPool:
        - [damage_while_shapeshifted]
        - [critical_strike_chance]
        - [ranks_of_the_heightened_senses_passive]
        - [ranks_of_the_quickshift_passive]

  - Insatiable Fury:
      itemType: chest armor
      minPower: 850
      affixPool:
        - [physical_damage]
        - [overpower_damage]
        - [damage_reduction_while_fortified]
        - [total_armor_while_in_werebear_form]

  - Mad Wolfs Glee:
      itemType: chest armor
      minPower: 860
      affixPool:
        - [maximum_life]
        - [poison_damage]
        - [damage_reduction_from_enemies_that_are_poisoned]
        - [movement_speed]

  - Storms Companion:
      itemType: pants
      minPower: 850
      affixPool:
        - [maximum_life]
        - [damage_reduction]
        - [companion_movement_speed]
        - [ranks_of_wolves]

  - Tempest Roar:
      itemType: helm
      minPower: 850
      affixPool:
        - [damage_while_shapeshifted]
        - [critical_strike_damage]
        - [maximum_spirit]
        - [poison_resistance]
      aspectValue: 15

  - Vasilys Prayer:
      itemType: helm
      minPower: 870
      affixPool:
        - [damage_while_shapeshifted]
        - [overpower_damage]
        - [maximum_life]
        - [lightning_resistance]

  - Waxing Gibbous:
      itemType: axe
      minPower: 900
      affixPool:
        - [critical_strike_damage]
        - [damage_to_close_enemies]
        - [damage_to_injured_enemies]
        - [life_on_kill]
      aspectValue: 1.0
