# Source: https://d4builds.gg/database/uniques/

Uniques:
  - Cowl of the Nameless:
      itemType: helm
      minPower: 900
      affixPool:
        - [crowd_control_duration]
        - [damage_reduction_from_close_enemies]
        - [cooldown_reduction]
        - [ranks_of_all_imbuement_skills]
      aspectValue: 20

  - Scoundrels Leathers:
      itemType: chest armor
      minPower: 900
      affixPool:
        - [trap_skill_damage]
        - [damage_to_enemies_affected_by_trap_skills]
        - [damage_reduction_from_enemies_affected_by_trap_skills]
        - [dodge_chance]
      aspectValue: 70

  - Skyhunter:
      itemType: bow
      minPower: 900
      affixPool:
        - [dexterity]
        - [critical_strike_damage]
        - [marksman_skill_damage]
        - [ranks_of_the_exploit_passive]
      aspectValue: 15

  - Windforce:
      itemType: bow
      minPower: 900
      affixPool:
        - [vulnerable_damage]
        - [core_skill_damage]
        - [ranks_of_the_impetus_passive]
        - [ranks_of_the_concussive_passive]
      aspectValue: 25

  - Eaglehorn:
      itemType: bow
      minPower: 900
      affixPool:
        - [critical_strike_chance]
        - [vulnerable_damage]
        - [physical_damage]
        - [damage_to_elites]
      aspectValue: 70

  - Condemnation:
      itemType: dagger
      minPower: 900
      affixPool:
        - [basic_skill_attack_speed]
        - [critical_strike_damage]
        - [core_skill_damage]
        - [damage_with_dualwielded_weapons]
      aspectValue: 30

  - Grasp Of Shadow:
      itemType: gloves
      minPower: 900
      affixPool:
        - [dexterity]
        - [attack_speed]
        - [shadow_clone_damage]
        - [ranks_of_all_core_skills]
      aspectValue: 29

  - Eyes in the Dark:
      itemType: pants
      minPower: 900
      affixPool:
        - [shadow_damage]
        - [damage_to_enemies_affected_by_trap_skills]
        - [maximum_life]
        - [damage_reduction]
      aspectValue: 40

  - Word of Hakan:
      itemType: amulet
      minPower: 860
      affixPool:
        - [movement_speed]
        - [ultimate_skill_damage]
        - [rain_of_arrows_skill_cooldown_reduction]
        - [ranks_of_all_imbuement_skills]
